'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.3607
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On



Partial Public Class _Default

    '''<summary>
    '''pnlStaff control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlStaff As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''lstAvailableJobs control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lstAvailableJobs As Global.System.Web.UI.WebControls.DataList

    '''<summary>
    '''lblAvailableJobs control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAvailableJobs As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lstCurrentJobs control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lstCurrentJobs As Global.System.Web.UI.WebControls.DataList

    '''<summary>
    '''lblCurrentJobs control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCurrentJobs As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lstQuestionaires control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lstQuestionaires As Global.System.Web.UI.WebControls.DataList

    '''<summary>
    '''lblQuestionaires control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblQuestionaires As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lstAnsweredQuestionaires control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lstAnsweredQuestionaires As Global.System.Web.UI.WebControls.DataList

    '''<summary>
    '''lblAnsweredQuestionaires control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAnsweredQuestionaires As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''pnlSalesman control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlSalesman As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''pnlBooking control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlBooking As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''lstCampaigns control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lstCampaigns As Global.System.Web.UI.WebControls.DataList

    '''<summary>
    '''lblNoCampaigns control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblNoCampaigns As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''grdPendingBookings control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents grdPendingBookings As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''lblNoPendingBookings control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblNoPendingBookings As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''grdRejectedBookings control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents grdRejectedBookings As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''lblNoRejectedBookings control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblNoRejectedBookings As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''grdConfirmedBookings control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents grdConfirmedBookings As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''lblNoConfirmedBookings control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblNoConfirmedBookings As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''grdSalesmanQuestionaires control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents grdSalesmanQuestionaires As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''lblNoSalesmanQuestionaires control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblNoSalesmanQuestionaires As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''pnlHeadOfSales control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlHeadOfSales As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''grdHOSConfirmed control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents grdHOSConfirmed As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''lblHOSNoComfirmed control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblHOSNoComfirmed As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''grdHOSQuestionaires control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents grdHOSQuestionaires As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''lblHOSNoQuestionaires control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblHOSNoQuestionaires As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''grdQuestionaireSummary control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents grdQuestionaireSummary As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''lblNoQuestionaireSummary control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblNoQuestionaireSummary As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''pnlProvider control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlProvider As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''grdOfferedBookings control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents grdOfferedBookings As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''lblNoOfferedBookings control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblNoOfferedBookings As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''grdAcceptedBookings control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents grdAcceptedBookings As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''lblNoAcceptedBookings control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblNoAcceptedBookings As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''grdNotAnsweredProviderQuestionaires control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents grdNotAnsweredProviderQuestionaires As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''lblNoNotAnsweredProviderQuestionaires control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblNoNotAnsweredProviderQuestionaires As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''grdAnsweredProviderQuestionaires control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents grdAnsweredProviderQuestionaires As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''lblNoAnsweredProviderQuestionaires control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblNoAnsweredProviderQuestionaires As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''upnMail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents upnMail As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''pnlContact control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlContact As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''tblPhoneNumbers control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tblPhoneNumbers As Global.System.Web.UI.WebControls.Table

    '''<summary>
    '''lnkMail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkMail As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''pnlMailForm control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlMailForm As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''txtMailFrom control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtMailFrom As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtMailBody control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtMailBody As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''cmdSendMail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmdSendMail As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''lblAlertMessage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAlertMessage As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Master property.
    '''</summary>
    '''<remarks>
    '''Auto-generated property.
    '''</remarks>
    Public Shadows ReadOnly Property Master() As BaltazarWeb.BalthazarMaster
        Get
            Return CType(MyBase.Master, BaltazarWeb.BalthazarMaster)
        End Get
    End Property
End Class
