'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.3082
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On



Partial Public Class login

    '''<summary>
    '''Table control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Table As Global.System.Web.UI.WebControls.Table

    '''<summary>
    '''TableRow1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TableRow1 As Global.System.Web.UI.WebControls.TableRow

    '''<summary>
    '''TableCell1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TableCell1 As Global.System.Web.UI.WebControls.TableCell

    '''<summary>
    '''Table1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Table1 As Global.System.Web.UI.WebControls.Table

    '''<summary>
    '''TableRow9 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TableRow9 As Global.System.Web.UI.WebControls.TableRow

    '''<summary>
    '''TableCell11 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TableCell11 As Global.System.Web.UI.WebControls.TableCell

    '''<summary>
    '''lblLogin control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblLogin As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''TableRow2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TableRow2 As Global.System.Web.UI.WebControls.TableRow

    '''<summary>
    '''cellCreateAccount control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cellCreateAccount As Global.System.Web.UI.WebControls.TableCell

    '''<summary>
    '''lblCreateAccount control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCreateAccount As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''TableRow3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TableRow3 As Global.System.Web.UI.WebControls.TableRow

    '''<summary>
    '''cellVerifyAccount control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cellVerifyAccount As Global.System.Web.UI.WebControls.TableCell

    '''<summary>
    '''lblVerifyAccount control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblVerifyAccount As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''TableRow4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TableRow4 As Global.System.Web.UI.WebControls.TableRow

    '''<summary>
    '''cellCreatedAccount control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cellCreatedAccount As Global.System.Web.UI.WebControls.TableCell

    '''<summary>
    '''lblRecoverPassword control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblRecoverPassword As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''TableRow5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TableRow5 As Global.System.Web.UI.WebControls.TableRow

    '''<summary>
    '''TableCell2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TableCell2 As Global.System.Web.UI.WebControls.TableCell

    '''<summary>
    '''cellLogin control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cellLogin As Global.System.Web.UI.WebControls.TableCell

    '''<summary>
    '''tblLogin control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tblLogin As Global.System.Web.UI.WebControls.Table

    '''<summary>
    '''TableHeaderRow3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TableHeaderRow3 As Global.System.Web.UI.WebControls.TableHeaderRow

    '''<summary>
    '''TableRow10 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TableRow10 As Global.System.Web.UI.WebControls.TableRow

    '''<summary>
    '''TableCell12 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TableCell12 As Global.System.Web.UI.WebControls.TableCell

    '''<summary>
    '''TableCell13 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TableCell13 As Global.System.Web.UI.WebControls.TableCell

    '''<summary>
    '''txtLogin control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtLogin As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''TableRow11 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TableRow11 As Global.System.Web.UI.WebControls.TableRow

    '''<summary>
    '''TableCell15 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TableCell15 As Global.System.Web.UI.WebControls.TableCell

    '''<summary>
    '''TableCell16 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TableCell16 As Global.System.Web.UI.WebControls.TableCell

    '''<summary>
    '''txtPassword control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPassword As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''rowLoginError control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rowLoginError As Global.System.Web.UI.WebControls.TableRow

    '''<summary>
    '''lblLoginError control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblLoginError As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''TableRow13 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TableRow13 As Global.System.Web.UI.WebControls.TableRow

    '''<summary>
    '''TableCell19 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TableCell19 As Global.System.Web.UI.WebControls.TableCell

    '''<summary>
    '''chkRememberMe control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkRememberMe As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''TableRow12 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TableRow12 As Global.System.Web.UI.WebControls.TableRow

    '''<summary>
    '''TableCell18 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TableCell18 As Global.System.Web.UI.WebControls.TableCell

    '''<summary>
    '''cmdLogin control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmdLogin As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''tblCreateAccount control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tblCreateAccount As Global.System.Web.UI.WebControls.Table

    '''<summary>
    '''TableHeaderRow1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TableHeaderRow1 As Global.System.Web.UI.WebControls.TableHeaderRow

    '''<summary>
    '''TableRow6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TableRow6 As Global.System.Web.UI.WebControls.TableRow

    '''<summary>
    '''TableCell4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TableCell4 As Global.System.Web.UI.WebControls.TableCell

    '''<summary>
    '''TableCell5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TableCell5 As Global.System.Web.UI.WebControls.TableCell

    '''<summary>
    '''txtUsername control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtUsername As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''TableRow7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TableRow7 As Global.System.Web.UI.WebControls.TableRow

    '''<summary>
    '''TableCell7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TableCell7 As Global.System.Web.UI.WebControls.TableCell

    '''<summary>
    '''TableCell8 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TableCell8 As Global.System.Web.UI.WebControls.TableCell

    '''<summary>
    '''txtEmail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtEmail As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''rowCreateUserError control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rowCreateUserError As Global.System.Web.UI.WebControls.TableRow

    '''<summary>
    '''lblCreateUserError control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCreateUserError As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''TableRow8 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TableRow8 As Global.System.Web.UI.WebControls.TableRow

    '''<summary>
    '''TableCell10 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TableCell10 As Global.System.Web.UI.WebControls.TableCell

    '''<summary>
    '''cmdCreateAccount control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmdCreateAccount As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''tblVerifyAccount control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tblVerifyAccount As Global.System.Web.UI.WebControls.Table

    '''<summary>
    '''TableHeaderRow2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TableHeaderRow2 As Global.System.Web.UI.WebControls.TableHeaderRow

    '''<summary>
    '''TableRow14 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TableRow14 As Global.System.Web.UI.WebControls.TableRow

    '''<summary>
    '''TableCell3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TableCell3 As Global.System.Web.UI.WebControls.TableCell

    '''<summary>
    '''TableCell6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TableCell6 As Global.System.Web.UI.WebControls.TableCell

    '''<summary>
    '''txtVerifyUsername control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtVerifyUsername As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''TableRow15 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TableRow15 As Global.System.Web.UI.WebControls.TableRow

    '''<summary>
    '''TableCell9 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TableCell9 As Global.System.Web.UI.WebControls.TableCell

    '''<summary>
    '''TableCell14 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TableCell14 As Global.System.Web.UI.WebControls.TableCell

    '''<summary>
    '''txtVerifyCode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtVerifyCode As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''TableRow16 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TableRow16 As Global.System.Web.UI.WebControls.TableRow

    '''<summary>
    '''TableCell23 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TableCell23 As Global.System.Web.UI.WebControls.TableCell

    '''<summary>
    '''TableCell24 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TableCell24 As Global.System.Web.UI.WebControls.TableCell

    '''<summary>
    '''txtWantedPassword control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtWantedPassword As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''TableRow20 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TableRow20 As Global.System.Web.UI.WebControls.TableRow

    '''<summary>
    '''TableCell25 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TableCell25 As Global.System.Web.UI.WebControls.TableCell

    '''<summary>
    '''TableCell26 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TableCell26 As Global.System.Web.UI.WebControls.TableCell

    '''<summary>
    '''txtRepeatpassword control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtRepeatpassword As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''rowVerifyError control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rowVerifyError As Global.System.Web.UI.WebControls.TableRow

    '''<summary>
    '''lblVerifyError control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblVerifyError As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''TableRow19 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TableRow19 As Global.System.Web.UI.WebControls.TableRow

    '''<summary>
    '''TableCell22 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TableCell22 As Global.System.Web.UI.WebControls.TableCell

    '''<summary>
    '''cmdVerify control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmdVerify As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''tblRecoverPassword control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tblRecoverPassword As Global.System.Web.UI.WebControls.Table

    '''<summary>
    '''txtRecoverUsername control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtRecoverUsername As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''rowRecoverStatus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rowRecoverStatus As Global.System.Web.UI.WebControls.TableRow

    '''<summary>
    '''lblRecoverStatus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblRecoverStatus As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''TableRow18 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TableRow18 As Global.System.Web.UI.WebControls.TableRow

    '''<summary>
    '''TableCell20 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TableCell20 As Global.System.Web.UI.WebControls.TableCell

    '''<summary>
    '''cmdRecover control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmdRecover As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''pnlWrongBrowser control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlWrongBrowser As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''lblBrowser control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblBrowser As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblBrowserVersion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblBrowserVersion As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Master property.
    '''</summary>
    '''<remarks>
    '''Auto-generated property.
    '''</remarks>
    Public Shadows ReadOnly Property Master() As BaltazarWeb.BalthazarMaster
        Get
            Return CType(MyBase.Master, BaltazarWeb.BalthazarMaster)
        End Get
    End Property
End Class
