'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.2012
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Animation.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        Friend ReadOnly Property balt() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("balt", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property rör1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("rör1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property rör10() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("rör10", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property rör11() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("rör11", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property rör12() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("rör12", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property rör13() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("rör13", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property rör14() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("rör14", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property rör15() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("rör15", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property rör16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("rör16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property rör17() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("rör17", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property rör18() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("rör18", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property rör19() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("rör19", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property rör2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("rör2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property rör20() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("rör20", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property rör21() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("rör21", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property rör22() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("rör22", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property rör23() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("rör23", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property rör24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("rör24", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property rör25() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("rör25", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property rör26() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("rör26", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property rör27() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("rör27", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property rör28() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("rör28", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property rör29() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("rör29", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property rör3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("rör3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property rör30() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("rör30", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property rör31() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("rör31", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property rör32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("rör32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property rör33() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("rör33", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property rör34() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("rör34", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property rör35() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("rör35", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property rör36() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("rör36", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property rör37() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("rör37", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property rör38() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("rör38", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property rör39() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("rör39", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property rör4() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("rör4", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property rör40() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("rör40", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property rör41() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("rör41", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property rör42() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("rör42", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property rör43() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("rör43", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property rör44() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("rör44", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property rör45() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("rör45", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property rör46() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("rör46", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property rör47() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("rör47", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property rör48() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("rör48", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property rör49() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("rör49", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property rör5() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("rör5", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property rör50() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("rör50", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property rör51() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("rör51", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property rör52() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("rör52", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property rör53() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("rör53", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property rör54() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("rör54", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property rör55() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("rör55", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property rör6() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("rör6", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property rör7() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("rör7", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property rör8() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("rör8", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property rör9() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("rör9", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
