
'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.3082
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On



Partial Public Class _default1

    '''<summary>
    '''pnlPendingCampaigns control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlPendingCampaigns As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''grdPendingCampaigns control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents grdPendingCampaigns As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''lblNoPendingCampaigns control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblNoPendingCampaigns As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''pnlAuthorizedCampaigns control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlAuthorizedCampaigns As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''grdAuthorizedCampaigns control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents grdAuthorizedCampaigns As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''lblNoAuthorizedCampaigns control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblNoAuthorizedCampaigns As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Master property.
    '''</summary>
    '''<remarks>
    '''Auto-generated property.
    '''</remarks>
    Public Shadows ReadOnly Property Master() As TrinityViewer.Trinity
        Get
            Return CType(MyBase.Master, TrinityViewer.Trinity)
        End Get
    End Property
End Class

